### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by tomthomasvempala** [Kameldieb/ascii_minecraft#3]
.\terminal_minecraft.c:7:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>

**Comment by ghost** [comment]
You don't have installed the library my guy.

**Comment by Ghgore** [comment]
I'm pretty sure the program is intended for Linux, try using WSL to run it :)

**Comment by iamthewallrus** [comment]
This is a Linux applet.
Until you decide to join the master race, I recommend you close this issue.
