### ISSUE TITLE
mc

### ISSUE THREAD

**Issue by JonathanRamos2002** [Kameldieb/ascii_minecraft#8]

**Comment by skyeredwood** [comment]
Please leave an actual issue or close this as it's unhelpful for new users who are seeking support about this project.

**Comment by JonathanRamos2002** [comment]
it’s been closed. i apologize about that, im new to github and didn’t
realize it was for issues.

**Comment by skyeredwood** [comment]
What did you think "Issues" meant? xD

_It's all good dw :)_
